name: Deployment to Studio

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        type: string
      network:
        description: "Subgraphs network to update"
        required: true
        type: choice
        options:
          - "ethereum"
          - "arbitrum"
          - "optimism"
          - "polygon"
          - "bnb"
          - "gnosis"
          - "base"
          - "moonbeam"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install graph-cli
        run: yarn global add @graphprotocol/graph-cli

      - name: Login to studio
        run: graph auth --studio ${{ secrets.GRAPH_STUDIO_ACCESS_TOKEN }}

      - name: Deploy subgraph
        run: yarn deploy:${{ github.event.inputs.network }} -l ${{ github.event.inputs.version }}
