name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Prepare subgraph
        # This could be any random network since we don't test
        # any network specific stuff
        run: yarn prepare:optimism

      - name: Generating code
        run: yarn codegen

      - name: Run graph tests
        run: yarn test
        timeout-minutes: 15
